const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
function load(key){let writes=0;const client={apiKey:{findFirst:async()=>key},event:{create:async({data})=>{writes++;return {...data,id:'event',status:'DRAFT',createdAt:new Date()}},findMany:async()=>[]},$executeRawUnsafe:async()=>1,$queryRawUnsafe:async()=>[{hits:1}]};const exports={};const context={exports,require:n=>n==='@prisma/client'?{PrismaClient:class{constructor(){return client}}}:require(n),process:{env:{}},Buffer,Date,console,setTimeout,clearTimeout};vm.runInNewContext(ts.transpileModule(fs.readFileSync('api/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);return {handler:exports.default,writes:()=>writes};}
async function request(key,token='pk_live_public',method='POST'){const app=load(key);let status=200;let payload;const res={setHeader(){},status(n){status=n;return this},json(v){payload=v;return this},end(){}};await app.handler({method,url:'/v1/events',headers:{authorization:'Bearer '+token},body:{name:'Event',starts_at:2000000000,venue_name:'Venue',city:'City'}},res);return {status,payload,writes:app.writes()};}
const key={id:'key',type:'PUBLISHABLE',mode:'LIVE',permissions:[],revokedAt:null,expiresAt:null,account:{id:'account',isActive:true}};
test('publishable key cannot create events',async()=>{const r=await request(key);assert.equal(r.status,403);assert.equal(r.writes,0)});
test('expired key denied before reads',async()=>{const r=await request({...key,type:'SECRET',expiresAt:new Date(0)},'sk_live_secret','GET');assert.equal(r.status,401)});
test('database key mode cannot disagree with token mode',async()=>{const r=await request({...key,type:'SECRET',mode:'TEST'},'sk_live_secret','GET');assert.equal(r.status,401)});
test('restricted key needs explicit event write permission',async()=>{const r=await request({...key,type:'RESTRICTED',permissions:['events:read']},'rk_live_restricted');assert.equal(r.status,403);assert.equal(r.writes,0)});
test('secret key creates a tenant scoped event',async()=>{const r=await request({...key,type:'SECRET'},'sk_live_secret');assert.equal(r.status,201);assert.equal(r.writes,1)});
test('inactive independent API account cannot use existing key',async()=>{const r=await request({...key,type:'SECRET',account:{id:'account',isActive:false}},'sk_live_secret','GET');assert.equal(r.status,401)});
